// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springroo.repository;

import com.springroo.repository.JscaffolderEntityRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JscaffolderEntityRepository_Roo_Jpa_Repository {
    
    declare @type: JscaffolderEntityRepository: @Transactional(readOnly = true);
    
}
